project_id = "pregaycgmaejwdgxetsd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "dual"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[functions.analyze-medicine]
verify_jwt = true

[functions.analyze-symptoms]
verify_jwt = true

[functions.send-driver-alerts]
verify_jwt = true

[functions.dispatch-ambulance]
verify_jwt = true

[functions.nearby-ambulances]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[auth]
enabled = true
additional_redirect_urls = ["https://127.0.0.1:3000/**"]
external_providers = []
enable_signup = true
enable_confirmations = false