// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pregaycgmaejwdgxetsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZWdheWNnbWFlandkZ3hldHNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjgyNzAsImV4cCI6MjA2OTU0NDI3MH0.FQreAFe82dnk8M4rARYsbMtPQ3pNu4WxeYJaJlgS7ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});